name: Lint

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Only run linting on pull requests
on:
  # Triggers the workflow when pull request created and updated
  pull_request:
    # Require manually kicking off CI by opening, reopening, or removing draft status.
    # NOTE when used as a repository ruleset, these types are ignored, and
    # opened, reopened, and synchronize are explicitly always enabled.
    types: [opened, ready_for_review, reopened]
  # Allows run of this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    # You do not appear to be able to use variables in the "uses" field.
    uses: NRLMMD-GEOIPS/geoips_ci/.github/workflows/reusable-lint.yaml@main
    # Only runs if the pull request is NOT a draft and this is not a test data repo
    if: >-
      github.event.pull_request.draft == false &&
      !contains(github.event.repository.name, 'test_data')
    permissions:
      contents: read
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  spell-check:
    # Only runs if the pull request is NOT a draft
    if: github.event.pull_request.draft == false
    name: Spell Check Changed Files
    # You do not appear to be able to use variables in the "uses" field.
    uses: NRLMMD-GEOIPS/geoips_ci/.github/workflows/reusable-cspell-spell-checking.yaml@main
    permissions:
      contents: read
      pull-requests: read
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
